spring.application.name=ratings-microservice
spring.main.allow-bean-definition-overriding=true

dean.logging.enabled=false
app.version=dev
dean.templates.path=./
dean.api.base-url=https://olympiadb.vstu.by/api/v1


# ?? PostgreSQL
spring.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/ratings
spring.datasource.username=postgres
spring.datasource.password=testpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.disable-swagger-default-url=false
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.docExpansion=none

# ???????????? (???? ???????????)

#Spring Security
auth.url=http://localhost:9989/token?grant_type=password
token.signing.key=SINGING.KEY

#Dean RepoAPI (for other projects)
dean.api.login=login
dean.api.password=pass
dean.api.clientId=deanClient
dean.api.clientSecret=StrongPassword

#Manager sockets
manager.host=localhost
manager.port=59898
manager.secretKey=secretkey1234567

#Telegram
dean.bot.token=telegram:api.token

#DevTools
spring.devtools.livereload.enabled=false

#Cache settings
caching.spring.ttl=60000

#Token validation
auth.resourceIds=dean
auth.validateUrl=http://127.0.0.1:1433/validate
auth.me.url=http://auth.vstu.by/api/v2/users/me
auth.needValidation=false
auth.public-urls=/ws/**,/swagger-ui/**,/swagger-resources/**,/v3/api-docs/**,/api/v1/public/**,/api/v1/schedule/**,/api/**

dean.temp.path=./temp/
dean.scripts.path=./scripts/
app.upload-dir.students=/photos/students

alerts.baseUrl=http://192.168.1.1:5000/
alerts.key=1

replica.main.url=http://192.168.1.1:10000/api/v1/replicas/ping
cors.allowed.origins=auth.vstu.by,support.vstu.by,registration.vstu.by,ebook.vstu.by,sdo.vstu.by,localhost,localhost:3003,localhost:3000,localhost:9989
spring.application.token=1

#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

